[[session]]
name = "Dev ğŸ“¥"
path = "~/Developer"
startup_command = "ls"

[[session]]
name = "dotfilesğŸ“"
path = "~/dotfiles"
startup_command = "ls"
[[session]]
name = "tmux configâš’ï¸"
path = "~/dotfiles/"
startup_command = "nvim .tmux.conf"
[[session]]
name = "nvim config âš’ï¸"
path = "~/dotfiles/.config/nvim/"
startup_command = "nvim"
