"$schema" = 'https://starship.rs/config-schema.json'
# A minimal left prompt
format = """
$directory\
$character"""
right_format = """
$git_branch\
$git_status\
$package\
$python\
$php\
$lua\
$cmd_duration"""
# add_newline = true
command_timeout = 200
[character]
success_symbol = '[\$](bold yellow) '
error_symbol = '[\$](bold red) '
[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
always_show_remote = true
style = "fg:green"
[cmd_duration]
format = 'ó°“… [$duration]($style) '
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'
[git_commit]
commit_hash_length = 4
style = 'bold blue'
[lua]
format = 'lua [ó°¢± $version](bold blue) '
[bun]
# format = ' [ğŸ‡ $version ](bold #a779b4)'
detect_files = [
  'package.json',
  '.node-version',
  'bun.lockb',
  'bunfig.toml'
]
detect_folders = ['node_modules']
[package]
symbol = "ğŸ“¦ "
style = "bold blue"
[php]
format = "[$symbol(php $version )]($style)"
[directory]
style = "cyan bold"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "ğŸ‘ˆ/"
[directory.substitutions]
"downloads" = "ï‰"
"Developer" = "î•"
